### ISSUE TITLE
Add support for perlcritic warnings (as opposed to just failures)

### ISSUE THREAD

**Issue by lohengrin332** [guillaumeaubert/App-GitHooks#13]
It would be nice to be able to warn the end user about certain perlcritic failures while still allowing the commit to proceed.  Example, long lines failures need not hold up a commit, but should still be pointed out to the user.

**Comment by guillaumeaubert** [comment]
This would be very useful to help with a softer reporting of non-critical errors indeed, and for App::GitHooks::Plugin::PerlCritic in particular.

Your example about long lines is however interesting in itself as well - I've filed #14 accordingly, for which this ticket is a prereq.

**Comment by guillaumeaubert** [comment]
Released with version 1.6.0.
