### ISSUE TITLE
Problem with hooks containing dashes in their names

### ISSUE THREAD

**Issue by jacobmaurer** [guillaumeaubert/App-GitHooks#15]
```Error detected in hook: >Can't locate object method "run_post-checkout" via package "App::GitHooks::Plugin::BranchChangeNotifier" at /home/jake/trunk2/cpan/cpan-5.010/lib/perl5/App/GitHooks/Hook.pm line 63, <DATA> line 1012.<.```

**Comment by guillaumeaubert** [comment]
Yikes. Thank you, @jacobmaurer!

8587267 will fix the issue, as you and I tested, but I'm going to hold off a release till tomorrow to think about whether I can write a good test to cover that case.

**Comment by guillaumeaubert** [comment]
Just released in v1.2.0. Thank you again for finding the bug, @jacobmaurer!
