### ISSUE TITLE
Uses File::Slurp, known to be buggy and vulnerable

### ISSUE THREAD

**Issue by karenetheridge** [guillaumeaubert/App-GitHooks#17]
e.g. look at https://rt.cpan.org/Ticket/Display.html?id=83126 and be dismayed

File::Slurp::Tiny and Path::Tiny are both excellent alternatives. See also http://shadow.cat/blog/matt-s-trout/mstpan-5/

**Comment by guillaumeaubert** [comment]
Thank you for pointing this out! I like your Path::Tiny recommendation, I'm going to replace File::Slurp with it and do a new release shortly.

**Comment by guillaumeaubert** [comment]
Released in v1.2.1. Thank you again, @karenetheridge !
