### ISSUE TITLE
Do not add relative paths to Perl include search path

### ISSUE THREAD

**Issue by ppisar** [guillaumeaubert/App-GitHooks#25]
bin/githooks uses `lib' module to include ./lib path. Allowing relative paths is a security issue as the attacker can prepare ./lib with malicious module there and then githooks script will execute the attackers code.

Please remove the `use lib' line.

The line is not needed for testing the script before installing it into the system as standard perl tools (./Build test) includes ./blib/{arch,lib} automatically.

**Comment by guillaumeaubert** [comment]
The use case was to be able to do a `git clone` and then run `./bin/githooks` without installing App::GitHooks, for testing local changes in the repository. But running `perl -I lib ./bin/githooks` will work fine for that purpose, so I've removed the corresponding line.

**Comment by guillaumeaubert** [comment]
Released in version 1.7.3. Thank you for reporting this issue!
